GCW-3569 load offer and item messages seperately
crossroads/admin.goodcity pull request #515
Opened 2021-05-05 05:36 UTC by swatijadhav

### Ticket Link: 
https://jira.crossroads.org.hk/browse/GCW-3569

### What does this PR do?
Load messages on offers and items separately.

2021-05-05 06:40 UTC, patrixr requested changes

2021-05-05 06:40 UTC, patrixr commented on app/routes/review_offer.js
> +    });
same as in the donor app, we likely want to await those promises

2021-05-20 03:52 UTC, steveyken approved these changes

2021-05-20 05:57 UTC, patrixr commented on app/routes/review_offer.js
> +    });
```suggestion
    return new AjaxPromise(
      `/offers/${offerId}`,
      "GET",
      _this.get("session.authToken"),
      { exclude_messages: "true" }
    ).then((data) => {
      this.store.pushPayload(data);
      return this.store.peekRecord("offer", offerId);
    });
```

`let _this = this;` is a very old pre-lambda pattern, which we will never need to ever use again :)

2021-05-20 05:59 UTC, patrixr commented on app/routes/review_offer.js
> +    });
also, you can probably use `await` instead of `.then`

2021-05-20 05:59 UTC, patrixr commented on app/routes/review_offer.js
> +    });
(none of this is a big deal, just side notes for the future)

2021-05-20 06:00 UTC, patrixr approved these changes

2021-05-21 05:03 UTC, merged